### ISSUE TITLE
In the comparison view, vertically align the same sections?

### ISSUE THREAD

**Issue by julesjacobs** [spooky/unitdb#23]
Say you want to compare the radar radius of t1 land scouts for each faction. The radar radius of the different scouts are not vertically aligned, so you have to visually search each list.

Another option is to highlight the corresponding property in all the units, if you hover over that property on one unit (like the other unit db does).

Sorry for spamming your issues list :|

**Comment by spooky** [comment]
Highlighting the same stat preferred. Old issue, closing.
