### ISSUE TITLE
Ipad Version

### ISSUE THREAD

**Issue by IDragonfire** [spooky/unitdb#27]
The UnitDB have a cool look on the Ipad:
![image](https://cloud.githubusercontent.com/assets/1217999/4898078/7dd97f28-640c-11e4-9f26-3659703f2e6a.jpg)

**Comment by spooky** [comment]
fixed by 2d08a76bbe1af4c2d53d1f259316b51028ef2833. Not the best fix in the world, but should do for now.

**Comment by IDragonfire** [comment]
Sometimes a hotfix is better then nothing ;)
