### ISSUE TITLE
Seraphim T2 Fighter

### ISSUE THREAD

**Issue by MutantGenepool** [spooky/unitdb#33]
Fighter/Bomber; Under Weapons the Shleo AA Autogun is listed twice.

**Comment by mrzechonek** [comment]
Not a bug, this aircraft indeed has 2 of those.

**Comment by Araamarmorth** [comment]
One nice thing that the old db does is grouping same weapons : http://content.faforever.com/faf/unitsDB/unit.php?bp=XSA0202,DEA0202

If this could be done here it would also be nice ;)

**Comment by spooky** [comment]
yeap, it's on the list: https://github.com/spooky/unitdb/issues/24
