### ISSUE TITLE
Add per mass cost stats

### ISSUE THREAD

**Issue by JeroenDeDauw** [spooky/unitdb#42]
Add `DPS per mass` and `HP per mass` stats. Such info is currently only available at http://wiki.faforever.com/index.php?title=FA_Stats_And_Calculations, though that is outdated.

For the DPS one, perhaps it is better to do `mass per DPS`, since otherwise all numbers are 0.x, with many 0.0x. This way round a T1 PD is 1.5 or so, and the rest more.

**Comment by spooky** [comment]
To be honest, I'd prefer this to stick to the raw data provided by game files. I try to keep additional stats to a minimum. I won't be able to provide every statistic for every player - there's just too many combinations. At some point, this will probably get a 'export to...' button which will allow you to get the data and manipulate it in any way/form you wish, Right now it's only json data and in a structure that's optimized for the app itself.

**Comment by JeroenDeDauw** [comment]
There might be a big number of combinations one can make, though the really useful ones do not seem all that many. DPS per mass to find how to maximize damage potential, and HP per mass to find how to maximize survivability.

**Comment by jasonnorthrup** [comment]
You could also take the product of HP and DPS and divide by mass, or any of the above divided by energy or build time as well. I wish I had the know-how to tabulate this analysis.
