### ISSUE TITLE
Allow sorting and filtering based on stats

### ISSUE THREAD

**Issue by JeroenDeDauw** [spooky/unitdb#43]
At http://wiki.faforever.com/index.php?title=FA_Stats_And_Calculations I can sort on the various stats. This is very useful when I try to find something like the highest DPS or DPS per mass units.

If (somewhat advanced) filtering is added, I could give commands such as "show me UEF land units sorted by ground weapons DPS per mass counting only weapons with a range of at least 70".

**Comment by spooky** [comment]
sounds like a job for excel...

**Comment by JeroenDeDauw** [comment]
An online spreadsheet with the stats in it that gets updated would be helpful yes. So would having this in a tool like the one you created here. The later seems more user friendly. In any case, I'd be very happy to see either.

**Comment by Cedricvdk** [comment]
yea!
