### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by JeroenDeDauw** [spooky/unitdb#44]
Question: when installing this tool locally, is it possible to also include unit data from mods? For instance to generate stats for Black Ops?

**Comment by spooky** [comment]
sure, the site itself uses a .json file which is generated from FAF files, if you modify it to include black ops data, it will display them

**Comment by Exotic-Retard** [comment]
how would you go about making it pull in a mod with hooks on top of the existing changes?
what i mean is a hooked mod has incomplete blueprints which are then merged on top of game code.
so the blueprint to json script would need to replicate that somehow, is that possible?

**Comment by spooky** [comment]
well, I can see a few was in which mods could be incorporated, though this is low priority so, other things come first

**Comment by Exotic-Retard** [comment]
im not asking you to do it, although that would be great.

i might have a bit of time in a couple of days (or might not) and im wondering if its something thats quite easy to do, in which case i could give it a try myself

**Comment by spooky** [comment]
Well, the code to pull out data from .bp files is there, the code to generate the .json from it as well, so the mod logic could work in a couple of ways. 

1) you create an index.<mod_name>.json that will then be used just as the regular one (though would need a switch somewhere on the ui as well as a bunch of new icons I guess) - the advantage of this is that it's the leas amount of work, the disadvantage is that it pulls in extra bytes over the wire, and the current index is rather big for a web resource (560kB for the smaller version). That means that for a mod like black ops, I'd expect a file or about 1MB)

2) you create an index.<mod_name>.json that will contain data on only the modded units, then modify the app to be able to merge these two. The merging should be simple. The up side is that you save on the bytes. The down side is that you get a bit of a performance degradation, cause the indexes need to be merged (which will result in a slighter longer 'initial' load time). The other 'bad' part is that it would require slight app modifications.

I'd go for option 1, cause I'm assuming most users are using a computer, not their mobile devices so the extra bytes shouldn't make too big of a difference.

In both cases, you'd need to squeeze in a mod selector somewhere.
Hope that helps.
