### ISSUE TITLE
Fix bugs for Downlord's FAF Client :-)

### ISSUE THREAD

**Issue by micheljung** [spooky/unitdb#51]
Hey there,

Just wanted to let you know that I integrated your unit DB into my client. Someone told me that it doesn't take some things into account though? I. e. The UEF Battleship should have 150 DPS per Gaus Cannon instead of 50.

I would love to keep your unit DB in my client, maybe you could rework it a bit? :)

**Comment by micheljung** [comment]
And if I may quote Exotic_Retard:
> oh and
> one thing it shoulnt do is take "ProjectilesPerOnFire" into any account
> its a false thing
> and in fact both unit dbs do that

**Comment by spooky** [comment]
Awesome. I'll try to scrape up some time to correct the issues, in the mean time, pull requests are always welcome ;)

**Comment by spooky** [comment]
Bug reported in #54. Closing as duplicate.
