### ISSUE TITLE
show firing cycle for units with one

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#54]
so the faf unit db shows the firing cycle correctly for units:

> fire cycle: 15 times 1 projectile every 0.2 seconds + 4.2 seconds reload = 7 seconds total, 225 damage total

while the spooky one shows it as

>   15 shots / 4 sec

which is 
a. less info
b. wrong
c. the dps is also calculated incorrectly and shows as 225 dp, likely due to the above

hope this helps

**Comment by Exotic-Retard** [comment]
the only thing the faf db does wrong is take ProjectilesPerOnfire into account. everything else seems ok. ProjectilesPerOnfire is a derelict value which does precisely nothing now. its not even in fa lua code at all.

**Comment by spooky** [comment]
Hopefully closed with 931f00bf2018145a05288f450909f94494d0fbdc
