### ISSUE TITLE
Prepending space or #%2 on every URL

### ISSUE THREAD

**Issue by Raistlfiren** [spooky/unitdb#58]
@spooky - It seems like the past few commits are breaking dev with `grunt serve`. I run `grunt serve` and try to load detailed views of the units or change views and it adds spaces in the URL encoding like http://localhost:9000/#!/#%2FXSA0202,XSS0304... or http://localhost:9000/#!/#%2Fby-class

If I get rid of the #%2, then it works just fine. This is doing it in Firefox and Chrome. Although, it seems to work just fine on the Github page view.

**Comment by spooky** [comment]
@Raistlfiren how can I reproduce this? what browser? what steps do you take?

**Comment by spooky** [comment]
not reproducable
