### ISSUE TITLE
Suggestion for background

### ISSUE THREAD

**Issue by UnDeFiNeD555** [spooky/unitdb#60]
I have made a new background for the unit page as i have noticed the current one doesnt have a good resolution. If you dont like it, please request some more i will be glad to provide you with as many as you want(i am a 3d modeler-amatuer vfx artist)
![downlord_background 2](https://user-images.githubusercontent.com/29611697/27401360-aa143074-56cb-11e7-9855-e6fe810c75a2.png)
![downlord_background](https://user-images.githubusercontent.com/29611697/27401454-fa28c192-56cb-11e7-9244-5cadfb93d358.png)

**Comment by spooky** [comment]
Thanks for the effort, but these are over 7MB ... this is A LOT for a small web app...
Anything below 2MB is ok.

**Comment by JeroenDeDauw** [comment]
Eh... you can just open the files in Gimp or whatever other app you have and save them to a file size you like?

**Comment by UnDeFiNeD555** [comment]
If you like the image I can just rerender it with more compression for maximum quality
Actually I am doing that right now. 😊

Sent from Mail for Windows 10

**Comment by UnDeFiNeD555** [comment]
[image: Ενσωματωμένη εικόνα 1]JPG format compressed and a little different.
Tell me if you like it.

2017-06-30 9:57 GMT+03:00 Mortifero <georgeseba.m.c@gmail.com>:
