### ISSUE TITLE
UEF Spearhead has Incorrect Information

### ISSUE THREAD

**Issue by Shinestar6** [spooky/unitdb#62]
The UEF Spearhead (XEL0306) is listed as firing 1 shot per 20 seconds, with a damage-per-shot of 800 damage, and damage-per-second of 80. This is incorrect. According to in-game stats of FAF, the Spearhead fires one salvo of 3 missiles every 10 seconds, dealing 800 damage per missile, for 2400 damage per salvo and 240 DPS.

So, according to the stats in-game, the stats on the database should say:

  | Missile (Normal) | 240dps
|                             | 800dmg
  | Fire cycle | 3 shots / 10 sec

**Comment by spooky** [comment]
Closed with 931f00bf2018145a05288f450909f94494d0fbdc
