### ISSUE TITLE
Cybran Hive not listed in structures

### ISSUE THREAD

**Issue by badbwoi** [spooky/unitdb#64]
If I select "base" the three Hive states are not listed.
![cybran hive_no_structure](https://user-images.githubusercontent.com/28671151/32283730-794a9506-bf25-11e7-8863-fcc83365d837.png)

**Comment by spooky** [comment]
Actually the bug here is that drone stations are listed. Hives are classified as build power which does not fall under 'base' filter.

**Comment by badbwoi** [comment]
Ah okay, makes sense! But since there is no "build power" filter, I kinda expect them under "base".

**Comment by spooky** [comment]
there seems to be an issue with the blueprint. Reported under https://github.com/FAForever/fa/issues/2300
