### ISSUE TITLE
improve "T2 Bot"

### ISSUE THREAD

**Issue by badbwoi** [spooky/unitdb#65]
Hello again :)

One suggestion to improve the overview of the main t2 tanks/bots and t2 range bots:
Move the "Ilshavoh" to the main group "T2 Heavy Tank" (Pillar, Rino, Obsidian) and rename both groups... 
![t2_bots](https://user-images.githubusercontent.com/28671151/33459877-ff31d6bc-d62b-11e7-9c6c-3cc501cde66e.png)
regards

**Comment by spooky** [comment]
nope, the chicken is a bot, strong as a tank, but a bot non the less
