### ISSUE TITLE
rearrange comparison tiles to be horizontal

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#69]
so what happens is when you compare a bunch of units, the tiles stack horizontally. thats great. whats not great is when you try to compare more than a certain amount, the next row of tiles goes under them. instead of doing it in rows of 5, why not just make all the tiles fit onto the first row, no matter how long it is, and add a horizontal scroller.

current behaviour that im talking about: ![](https://i.imgur.com/yk79W0L.jpg)
here we can see 12 units compared, 5 fit in the first row, 6th fits in second row under the 5th unit. then 5 more on the third row, and then one last unit on the 4th row, instead of one big row of 12 units long.

**Comment by spooky** [comment]
well, because all of these may have a different layout, it's kind of hard to pick the best option. Each will be in a way faulty :/ but I guess I can try to use something like https://masonry.desandro.com/layout.html

**Comment by Exotic-Retard** [comment]
what im saying is that until you compare 6 or more units i would argue that the display is pretty much ideal.

this is because the most sensible comparison is side by side so units which have similarities with each other have these stats shown on the same level, so your eye expects where to go next, instead of jumping around.

if the units are totally different like the mex and destroyer thats fine imo since you would only want to compare the relevant info like mass cost which is aligned already for example.

there can be other improvements made like the sections rearranging or stretching themselves out to align better but imo thats out of the scope of this particular issue :>
