### ISSUE TITLE
compact view

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#72]
i just want to say that i much prefer the by class view to the default which imo is too many icons in one place. great job on the by class view. (consider making it the default?)

one issue with it however is that it takes quite some scrolling, each row taking up a significant amount of space.

a compacted version of this where you dont see the unit icon but only strategic icon and description on the side like currently, would make each row a lot thinner and therefore need less scrolling.

**Comment by spooky** [comment]
Added a button in the top right of the by-class view.  Enjoy
Also, the app now remembers the last view that was visited, so if you bookmark the root url, you should get 'your preferred default' (kept in browser local storage)
