### ISSUE TITLE
rearrange units in by class view by type then by tech

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#73]
what i mean is this:
![](https://i.imgur.com/EKXuzE6.png)
here we can see everything arranged by tech level. thats nice and logical and works most of the time, but there are a couple of exceptions where it could be better.
here we see the t1 engineer and t2 engineer, and the t3 engineer which is very likely to be compared to them, being their t3 counterpart is all the way down. after the t1 engineering drone (shouldnt that have been listed at the top? its t1 in between t2 and t3 units :/)

it would have made more sense for this section to be arranged as such:
acus, sacus, T1,2,3 engineers, t2 field engineer, t2 engineering stations, engineering drones in either order

of course, this applies to the rest of the db as well, although a good portion of it is already arranged pretty well as is

**Comment by spooky** [comment]
Feel free to make a pull request. The order is quite easy to change. Starts [here](https://github.com/spooky/unitdb/blob/master/app/js/UnitDecorator.js#L97).

**Comment by spooky** [comment]
I guess this one is closed with https://github.com/spooky/unitdb/pull/74. Looking forward to the rest.
