### ISSUE TITLE
link redirection issues

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#76]
due to how the website does caching or something, it often redirects you to things you dont want.

for example, if i have two tabs open, 
one on http://spooky.github.io/unitdb/#/UEL0301,URL0301,UAL0301,XSL0301
and then click a link to http://spooky.github.io/unitdb/#/
in a second tab, i get redirected to the first url. this makes it fairly annoying to use since clicking links to it pointed at units often doesnt work.

what would be good is to store the view settings where appropriate, and then redirect part of the link so that it applies the view settings but not the actual unit comparison tables.

or something.

**Comment by spooky** [comment]
Yeah, remembering 'last view' was a failed attempt to tackle the 'default view' problem. I removed it. Still storing selected preferences like compact view but the page won't redirect to 'by class' or 'by kind' views any more.
