### ISSUE TITLE
incorrect dps calculations for Dot weapons

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#77]
the damage per shot for those is incorrect.
http://spooky.github.io/unitdb/#/DEA0202,UEA0103
currently those list as doing something like 4 damage per bomb.
the damage should be calculated as 
`Damage*(DoTPulses or 1) + (InitialDamage or 0)`

**Comment by spooky** [comment]
this was calculated as
`(initial + w.Damage * w.DoTPulses * w.MuzzleSalvoSize) /  unitDb.DpsCalculator.rateInverse(w)`
Changed to the suggested formula.
