### ISSUE TITLE
incorrect DPS for UEF t3 maa

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#79]
ok this ones a bit difficult xD

1. it seems to have the salvosize done incorrectly for it.
`RackFireTogether = true,` so the salvo size _SHOULD BE_ the number of muzzle bones in the RackBones table
however, the `MuzzleSalvoDelay` is greater than 0, so the RackFireTogether is overriden. indeed the unit fires one projectile at a time in game.

This means that its `TrueSalvoSize = MuzzleSalvoSize*Damage` which in this case is 12*100 = 1200

2.the reload time on this thing is also just as strange.
`RateOfFire = 1` but there are some other stats that end up overriding it.
the total firing cycle for the 12 muzzles is 1.1 seconds, which is already longer than the reload time. Normally what happens in this case is the weapon can wait twice. but this isnt always true! (confusing i know)
weapons in supcom also have RackSalvoReloadTime and RackSalvoChargeTime, both of which are specified in this unit.

so HERE, the weapon waits for 1 second, then fires for 1.1 seconds, then reloads for 4.5 seconds for a total time of 6.6 seconds.

heres some example code (Lua mind you) that gives the correct answer:

```
local trueReload = math.max(0.1*math.floor((10 / weapon.RateOfFire) + 0.5), 0.1)

trueReload = math.max((weapon.RackSalvoChargeTime or 0) + (weapon.RackSalvoReloadTime or 0) + (weapon.MuzzleSalvoDelay or 0)*((weapon.MuzzleSalvoSize or 1)-1), trueReload)
```
note here the `weapon` table is the weapon blueprint. so weapon.RackSalvoChargeTime  is reading the value from the unit blueprint, in the weapon entry for each weapon.

**Comment by spooky** [comment]
@Exotic-Retard is this a formula that's applied to all units or just this one? or a group....?
