### ISSUE TITLE
wrecks "incorrect" mass value

### ISSUE THREAD

**Issue by Exotic-Retard** [spooky/unitdb#82]
this is kinda confusing tbh.

so in supcom wrecks are 90% of the mass of their parent unit, but their hp is also 90% of that, and since their mass value is proportional to hp, in reality their mass value is 81% of the unit.

so that means that for example the t2 mex should leave a 900*0.9*0.9 = 729 mass value wreck.

so maybe, it might be better to put 81% instead of its "actual" mass value, since thats what gets dumped in the game.

**Comment by spooky** [comment]
Fixed. Needs a cache clear though :/
